---
- name: 'Download Wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: /tmp/wordpress.tar.gz
  become: yes
    
- name: 'Descompactar Arquivo'
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Copia arquivo de configuração Wordpress'
  copy: 
    src: "{{ wp_inst_dir }}/wp-config-sample.php"
    dest: "{{ wp_inst_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura variaveis de configuração Wordpress'
  replace:
    path: "{{ wp_inst_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items: 
    - { regex: 'localhost', value: "{{ wp_db_ip }}"}
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_db_user }}"}
    - { regex: 'password_here', value: "{{ wp_db_pass }}"}
  become: yes

- name: 'Configurando Apache'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache