---
- name: 'Istalando Pacotes'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes  
  with_items:
    - mysql-server-5.7
    - python-mysqldb

- name: 'Cria o banco do MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes

- name: 'Cria usuário do banco MySQL'
  mysql_user:
    name: "{{ wp_db_user }}"
    host: "{{ item }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"
  with_items:
    - "{{ wp_host_ip }}"
  become: yes
  notify:
    - restart mysql

- name: 'Copia arquivo de configuração Mysql'
  copy: 
    src: files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  become: yes
  notify:
    - restart mysql