---
- name: 'Istalando Pacotes'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes  
  with_items:
    - php
    - apache2
    - libapache2-mod-php
    - php-gd
    - php-ssh2
    - mcrypt
    - php-mysql